"""
Model Analyzer
============

Analyzes model internals:
- Weight statistics
- Activation patterns
- Attention analysis
- Redundancy detection
- Structural patterns
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple
from enum import Enum
import torch
import torch.nn as nn
import numpy as np
from collections import defaultdict


class RedundancyType(Enum):
    """Types of redundancy in neural networks."""
    LOW_RANK = "low_rank"           # Weight matrix is approximately low-rank
    DEAD_NEURONS = "dead_neurons"   # Some neurons never activate
    DEAD_ATTENTION = "dead_attention"  # Attention heads that do nothing
    DUPLICATED_WEIGHTS = "duplicated_weights"  # Identical weight patterns
    SPARSE_ACTIVATION = "sparse_activation"  # Many zeros in activations
    CORRELATED_LAYERS = "correlated_layers"  # Layers with similar weights


@dataclass
class LayerAnalysis:
    """Analysis of a single layer."""
    name: str
    layer_type: str
    shape: Tuple[int, ...]
    num_parameters: int
    size_bytes: int
    
    # Statistics
    mean: float
    std: float
    min: float
    max: float
    sparsity: float  # Fraction of near-zero values
    
    # Redundancy
    redundancy_type: Optional[RedundancyType] = None
    redundancy_score: float = 0.0  # 0-1, higher = more redundant
    
    # Low-rank analysis
    singular_values: Optional[List[float]] = None
    explained_variance_ratio: float = 0.0
    
    # Activation analysis (if available)
    activation_mean: float = 0.0
    activation_sparsity: float = 0.0


@dataclass
class AttentionAnalysis:
    """Analysis of attention patterns."""
    layer_name: str
    num_heads: int
    head_dim: int
    
    # Per-head statistics
    head_importance: List[float]
    head_redundancy: List[float]
    
    # Patterns
    attention_entropy: float  # How distributed is attention
    dominant_pattern: str  # "uniform", "local", "diagonal", "sparse"
    
    # Redundancy
    redundant_heads: List[int]  # Indices of redundant heads


@dataclass
class ModelCard:
    """
    Complete analysis card for a model.
    
    Generated by ModelAnalyzer.
    """
    model_name: str
    total_parameters: int
    total_size_bytes: int
    
    # Layer analysis
    layers: Dict[str, LayerAnalysis]
    
    # Attention analysis
    attention_layers: Dict[str, AttentionAnalysis]
    
    # Global statistics
    global_mean: float
    global_std: float
    weight_distribution: Dict[str, float]  # e.g., {"uniform": 0.1, "normal": 0.9}
    
    # Redundancy summary
    redundancy_summary: Dict[RedundancyType, float]  # Type -> fraction of params
    
    # Compression potential
    estimated_quantization_gain: float  # Expected 2-4x
    estimated_pruning_gain: float  # Expected 1.5-3x
    estimated_low_rank_gain: float  # Expected 1.5-3x
    
    # Unique insights
    insights: List[str]


@dataclass
class AnalysisResult:
    """Result of running analysis."""
    model_name: str
    success: bool
    model_card: Optional[ModelCard] = None
    error: Optional[str] = None
    layers_analyzed: int = 0
    time_seconds: float = 0.0


class ModelAnalyzer:
    """
    Comprehensive model analyzer.
    
    Analyzes:
    - Weight statistics
    - Activation patterns
    - Attention mechanisms
    - Redundancy
    - Compression potential
    """
    
    def __init__(self):
        self.results: List[AnalysisResult] = []
    
    def analyze(
        self,
        model: nn.Module,
        model_name: str = "unknown",
        sample_inputs: Optional[List[torch.Tensor]] = None,
        activation_hook: bool = True,
    ) -> AnalysisResult:
        """
        Analyze a model.
        
        Args:
            model: PyTorch model to analyze
            model_name: Name for identification
            sample_inputs: Optional sample inputs for activation analysis
            activation_hook: Whether to hook activations
        
        Returns:
            AnalysisResult with full analysis
        """
        import time
        start = time.time()
        
        try:
            # Initialize storage
            layer_analyses: Dict[str, LayerAnalysis] = {}
            attention_analyses: Dict[str, AttentionAnalysis] = {}
            
            # Collect activations if needed
            activations = {}
            if activation_hook and sample_inputs:
                hooks = self._register_activation_hooks(model, activations)
            
            # Forward pass if we have inputs
            if sample_inputs:
                model.eval()
                with torch.no_grad():
                    try:
                        for inp in sample_inputs:
                            if isinstance(inp, (list, tuple)):
                                model(*inp)
                            else:
                                model(inp)
                    except Exception:
                        pass  # Ignore forward pass errors
            
            # Remove hooks
            if activation_hook and sample_inputs:
                for hook in hooks:
                    hook.remove()
            
            # Analyze each parameter
            for name, param in model.named_parameters():
                if not param.requires_grad:
                    continue
                
                analysis = self._analyze_parameter(name, param, activations.get(name))
                layer_analyses[name] = analysis
            
            # Analyze attention if present
            for name, module in model.named_modules():
                if "attention" in name.lower() or isinstance(module, nn.MultiheadAttention):
                    analysis = self._analyze_attention(module, name)
                    if analysis:
                        attention_analyses[name] = analysis
            
            # Calculate redundancy summary
            redundancy_summary = self._calculate_redundancy(layer_analyses)
            
            # Estimate compression potential
            compression_estimates = self._estimate_compression(layer_analyses)
            
            # Generate insights
            insights = self._generate_insights(layer_analyses, attention_analyses, redundancy_summary)
            
            # Calculate global statistics
            all_params = list(layer_analyses.values())
            if all_params:
                global_mean = np.mean([l.mean for l in all_params])
                global_std = np.mean([l.std for l in all_params])
            else:
                global_mean = 0.0
                global_std = 1.0
            
            # Build model card
            model_card = ModelCard(
                model_name=model_name,
                total_parameters=sum(l.num_parameters for l in layer_analyses.values()),
                total_size_bytes=sum(l.size_bytes for l in layer_analyses.values()),
                layers=layer_analyses,
                attention_layers=attention_analyses,
                global_mean=global_mean,
                global_std=global_std,
                weight_distribution={},  # Would calculate
                redundancy_summary=redundancy_summary,
                estimated_quantization_gain=compression_estimates["quantization"],
                estimated_pruning_gain=compression_estimates["pruning"],
                estimated_low_rank_gain=compression_estimates["low_rank"],
                insights=insights,
            )
            
            result = AnalysisResult(
                model_name=model_name,
                success=True,
                model_card=model_card,
                layers_analyzed=len(layer_analyses),
                time_seconds=time.time() - start,
            )
            
            self.results.append(result)
            return result
            
        except Exception as e:
            result = AnalysisResult(
                model_name=model_name,
                success=False,
                error=str(e),
            )
            self.results.append(result)
            return result
    
    def _analyze_parameter(
        self,
        name: str,
        param: torch.Tensor,
        activation: Optional[torch.Tensor] = None,
    ) -> LayerAnalysis:
        """Analyze a single parameter."""
        # Basic stats
        data = param.detach().float()
        mean = data.mean().item()
        std = data.std().item()
        min_val = data.min().item()
        max_val = data.max().item()
        
        # Sparsity
        sparsity = (data.abs() < 0.01).float().mean().item()
        
        # Determine layer type
        layer_type = self._infer_layer_type(name, param)
        
        # Redundancy analysis
        redundancy_type, redundancy_score = self._analyze_redundancy(data, param.shape)
        
        # Low-rank analysis (if 2D)
        singular_values = None
        explained_variance_ratio = 0.0
        if len(param.shape) == 2:
            try:
                _, s, _ = torch.svd(data)
                singular_values = s[:20].tolist()  # Top 20
                total_var = (s ** 2).sum().item()
                if total_var > 0:
                    explained_variance_ratio = (s[:10] ** 2).sum().item() / total_var
            except Exception:
                pass
        
        return LayerAnalysis(
            name=name,
            layer_type=layer_type,
            shape=tuple(param.shape),
            num_parameters=param.numel(),
            size_bytes=param.numel() * param.element_size(),
            mean=mean,
            std=std,
            min=min_val,
            max=max_val,
            sparsity=sparsity,
            redundancy_type=redundancy_type,
            redundancy_score=redundancy_score,
            singular_values=singular_values,
            explained_variance_ratio=explained_variance_ratio,
            activation_mean=activation.mean().item() if activation is not None else 0.0,
            activation_sparsity=(activation.abs() < 0.01).float().mean().item() if activation is not None else 0.0,
        )
    
    def _analyze_attention(
        self,
        module: nn.Module,
        name: str,
    ) -> Optional[AttentionAnalysis]:
        """Analyze an attention module."""
        # Basic info
        if isinstance(module, nn.MultiheadAttention):
            num_heads = module.num_heads
            embed_dim = module.embed_dim
            head_dim = embed_dim // num_heads
        else:
            return None
        
        # Placeholder analysis
        return AttentionAnalysis(
            layer_name=name,
            num_heads=num_heads,
            head_dim=head_dim,
            head_importance=[1.0 / num_heads] * num_heads,
            head_redundancy=[0.0] * num_heads,
            attention_entropy=0.0,
            dominant_pattern="unknown",
            redundant_heads=[],
        )
    
    def _infer_layer_type(self, name: str, param: torch.Tensor) -> str:
        """Infer layer type from parameter name."""
        name_lower = name.lower()
        
        if "weight" not in name_lower and "bias" not in name_lower:
            return "unknown"
        
        if "embedding" in name_lower:
            return "embedding"
        elif "q_proj" in name_lower or "k_proj" in name_lower or "v_proj" in name_lower:
            return "attention_projection"
        elif "o_proj" in name_lower or "output" in name_lower:
            return "output_projection"
        elif "gate_proj" in name_lower or "up_proj" in name_lower or "down_proj" in name_lower:
            return "mlp_projection"
        elif "lm_head" in name_lower or "final" in name_lower:
            return "lm_head"
        elif len(param.shape) == 2:
            return "linear"
        elif len(param.shape) == 1:
            return "bias"
        else:
            return "other"
    
    def _analyze_redundancy(
        self,
        data: torch.Tensor,
        shape: torch.Size,
    ) -> Tuple[Optional[RedundancyType], float]:
        """Analyze redundancy in a parameter."""
        if len(shape) != 2:
            return None, 0.0
        
        # Check for low-rank structure
        try:
            _, s, _ = torch.svd(data)
            total_var = (s ** 2).sum()
            if total_var > 0:
                explained_90 = ((s[:shape[0]//10] ** 2).sum() / total_var).item()
                if explained_90 > 0.95:
                    return RedundancyType.LOW_RANK, 0.8
                elif explained_90 > 0.85:
                    return RedundancyType.LOW_RANK, 0.5
        except Exception:
            pass
        
        # Check for sparsity
        sparsity = (data.abs() < 0.01).float().mean().item()
        if sparsity > 0.5:
            return RedundancyType.SPARSE_ACTIVATION, sparsity
        
        return None, 0.0
    
    def _calculate_redundancy(
        self,
        layers: Dict[str, LayerAnalysis],
    ) -> Dict[RedundancyType, float]:
        """Calculate redundancy summary across all layers."""
        summary: Dict[RedundancyType, float] = defaultdict(float)
        total_params = 0
        
        for layer in layers.values():
            total_params += layer.num_parameters
            if layer.redundancy_type:
                summary[layer.redundancy_type] += layer.num_parameters * layer.redundancy_score
        
        # Normalize
        for rtype in summary:
            summary[rtype] /= total_params if total_params > 0 else 1
        
        return dict(summary)
    
    def _estimate_compression(
        self,
        layers: Dict[str, LayerAnalysis],
    ) -> Dict[str, float]:
        """Estimate potential compression gains."""
        # Quantization: 2-4x depending on dtype
        quantization_gain = 2.0  # Conservative
        
        # Pruning: 1.5-3x based on sparsity
        avg_sparsity = np.mean([l.sparsity for l in layers.values()]) if layers else 0.0
        pruning_gain = 1.0 / (1.0 - avg_sparsity) if avg_sparsity < 1 else 1.0
        
        # Low-rank: 1.5-3x based on explained variance
        avg_low_rank = np.mean([l.explained_variance_ratio for l in layers.values() if l.singular_values]) if layers else 0.0
        low_rank_gain = 1.0 / avg_low_rank if avg_low_rank > 0.1 else 1.0
        
        return {
            "quantization": quantization_gain,
            "pruning": min(3.0, pruning_gain),
            "low_rank": min(3.0, low_rank_gain),
        }
    
    def _generate_insights(
        self,
        layers: Dict[str, LayerAnalysis],
        attention: Dict[str, AttentionAnalysis],
        redundancy: Dict[RedundancyType, float],
    ) -> List[str]:
        """Generate insights from analysis."""
        insights = []
        
        # Redundancy insights
        if redundancy.get(RedundancyType.LOW_RANK, 0) > 0.3:
            insights.append(
                f"Low-rank redundancy detected in {redundancy[RedundancyType.LOW_RANK]:.0%} of parameters. "
                "Consider SVD decomposition."
            )
        
        if redundancy.get(RedundancyType.SPARSE_ACTIVATION, 0) > 0.2:
            insights.append(
                f"Sparse activations found in {redundancy[RedundancyType.SPARSE_ACTIVATION]:.0%} of parameters. "
                "Consider pruning."
            )
        
        # Layer type distribution
        layer_types = defaultdict(int)
        for layer in layers.values():
            layer_types[layer.layer_type] += layer.num_parameters
        
        if layer_types:
            total = sum(layer_types.values())
            most_common = max(layer_types.items(), key=lambda x: x[1])
            insights.append(
                f"Most common layer type: {most_common[0]} ({most_common[1]/total:.0%} of parameters)"
            )
        
        # Sparsity insights
        avg_sparsity = np.mean([l.sparsity for l in layers.values()]) if layers else 0.0
        if avg_sparsity > 0.1:
            insights.append(
                f"Average weight sparsity: {avg_sparsity:.0%}. "
                f"Potential pruning gain: {1.0/(1.0-avg_sparsity):.1f}x"
            )
        
        return insights
    
    def _register_activation_hooks(
        self,
        model: nn.Module,
        activations: Dict,
    ) -> List:
        """Register hooks to capture activations."""
        hooks = []
        
        def hook_fn(module, input, output):
            name = str(id(module))
            if isinstance(output, torch.Tensor):
                activations[name] = output.detach()
            elif isinstance(output, (list, tuple)):
                activations[name] = output[0].detach() if output[0] is not None else None
        
        for name, module in model.named_modules():
            if isinstance(module, (nn.Linear, nn.Conv2d, nn.MultiheadAttention)):
                hooks.append(module.register_forward_hook(hook_fn))
        
        return hooks
    
    def summary(self) -> str:
        """Generate a summary of all analyses."""
        lines = [
            "=" * 60,
            "MODEL ANALYZER SUMMARY",
            "=" * 60,
            "",
            f"Total analyses: {len(self.results)}",
        ]
        
        for result in self.results:
            status = "✅" if result.success else "❌"
            lines.append(f"\n{status} {result.model_name}")
            if result.success and result.model_card:
                card = result.model_card
                lines.append(f"  Parameters: {card.total_parameters:,}")
                lines.append(f"  Size: {card.total_size_bytes / 1e9:.2f} GB")
                lines.append(f"  Layers analyzed: {result.layers_analyzed}")
                lines.append(f"  Quantization gain: {card.estimated_quantization_gain:.1f}x")
                lines.append(f"  Pruning gain: {card.estimated_pruning_gain:.1f}x")
                
                if card.insights:
                    lines.append("  Insights:")
                    for insight in card.insights[:3]:
                        lines.append(f"    - {insight}")
        
        return "\n".join(lines)
